const puppeteer = require("puppeteer")
const fs = require("fs")

// Find an installed Chromium-based browser (same logic as ai.service.js)
const CANDIDATE_BROWSERS = [
    process.env.PUPPETEER_EXECUTABLE_PATH,
    "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
    "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe",
    "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
    "/usr/bin/google-chrome",
    "/usr/bin/google-chrome-stable",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
    "/usr/bin/microsoft-edge",
].filter(Boolean)

function getBrowserExecutable() {
    for (const p of CANDIDATE_BROWSERS) {
        try {
            if (fs.existsSync(p)) return p
        } catch { /* ignore */ }
    }
    return null
}

/**
 * Escape HTML entities for safe rendering in the export HTML.
 */
function escapeHtml(str) {
    if (typeof str !== "string") return ""
    return str
        .replace(/&/g, function() { return "&" + "amp;" })
        .replace(/</g, function() { return "&" + "lt;" })
        .replace(/>/g, function() { return "&" + "gt;" })
        .replace(/"/g, function() { return "&" + "quot;" })
        .replace(/'/g, function() { return "&" + "#39;" })
}

/**
 * @name generatePdfFromHtml
 * @description Convert HTML to a PDF buffer using installed Chrome/Edge or bundled Chromium.
 */
async function generatePdfFromHtml(htmlContent) {
    const executablePath = getBrowserExecutable()
    const launchOptions = executablePath ? { executablePath } : {}
    const browser = await puppeteer.launch(launchOptions)

    try {
        const page = await browser.newPage()
        await page.setContent(htmlContent, { waitUntil: "networkidle0" })

        const pdfResult = await page.pdf({
            format: "A4",
            margin: {
                top: "20mm",
                bottom: "20mm",
                left: "15mm",
                right: "15mm"
            }
        })

        const pdfBuffer = Buffer.from(pdfResult)

        if (pdfBuffer.length === 0) {
            throw new Error("PDF generation returned an empty buffer.")
        }

        return pdfBuffer
    } finally {
        await browser.close()
    }
}

/**
 * @name baseHtml
 * @description Build the base HTML document for exports.
 */
function baseHtml(title, bodyHtml) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>${escapeHtml(title)}</title>
    <style>
        body { font-family: "Segoe UI", Arial, sans-serif; color: #1a1f27; line-height: 1.6; padding: 8px; }
        h1 { color: #4f46e5; border-bottom: 3px solid #4f46e5; padding-bottom: 8px; }
        h2 { color: #1e293b; margin-top: 24px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
        h3 { color: #334155; }
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 16px 0; }
        .info-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px 16px; }
        .info-card strong { display: block; color: #64748b; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
        .info-card span { font-size: 16px; font-weight: 500; }
        ul { margin: 8px 0; padding-left: 20px; }
        li { margin: 4px 0; }
        .score-badge { display: inline-block; background: #4f46e5; color: white; border-radius: 999px; padding: 4px 14px; font-weight: 600; }
        .section { margin-bottom: 20px; }
        .meta { color: #64748b; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
        th { background: #f1f5f9; }
        code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-size: 13px; }
        pre { background: #0f172a; color: #e2e8f0; padding: 16px; border-radius: 8px; overflow-x: auto; font-size: 13px; }
        .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 12px; color: #94a3b8; font-size: 12px; text-align: center; }
    </style>
</head>
<body>
    ${bodyHtml}
    <div class="footer">Generated by AI Interview Preparation Platform</div>
</body>
</html>`
}

/**
 * @name exportInterviewReport
 * @description Export an interview report as PDF.
 */
async function exportInterviewReport(report) {
    const skillGaps = (report.skillGaps || []).map(g =>
        `<li>${escapeHtml(g.skill)} <span class="meta">(${escapeHtml(g.severity)} priority)</span></li>`
    ).join("")

    const technicalQuestions = (report.technicalQuestions || []).map((q, i) =>
        `<div class="section">
            <h3>Q${i + 1}: ${escapeHtml(q.question)}</h3>
            <p class="meta"><strong>Intention:</strong> ${escapeHtml(q.intention)}</p>
            <p><strong>Suggested approach:</strong> ${escapeHtml(q.answer)}</p>
        </div>`
    ).join("")

    const behavioralQuestions = (report.behavioralQuestions || []).map((q, i) =>
        `<div class="section">
            <h3>Q${i + 1}: ${escapeHtml(q.question)}</h3>
            <p class="meta"><strong>Intention:</strong> ${escapeHtml(q.intention)}</p>
            <p><strong>Suggested approach:</strong> ${escapeHtml(q.answer)}</p>
        </div>`
    ).join("")

    const prepPlan = (report.preparationPlan || []).map(p =>
        `<div class="section">
            <h3>Day ${p.day}: ${escapeHtml(p.focus)}</h3>
            <ul>${(p.tasks || []).map(t => `<li>${escapeHtml(t)}</li>`).join("")}</ul>
        </div>`
    ).join("")

    const bodyHtml = `
        <h1>Interview Report</h1>
        <p class="meta">${escapeHtml(report.title || "")}</p>

        <div class="info-grid">
            <div class="info-card"><strong>Match Score</strong><span class="score-badge">${report.matchScore ?? "N/A"}/100</span></div>
            <div class="info-card"><strong>Generated</strong><span>${new Date(report.createdAt).toLocaleDateString()}</span></div>
        </div>

        <h2>Skill Gaps</h2>
        ${skillGaps ? `<ul>${skillGaps}</ul>` : "<p class='meta'>No skill gaps identified.</p>"}

        <h2>Technical Questions</h2>
        ${technicalQuestions || "<p class='meta'>None generated.</p>"}

        <h2>Behavioral Questions</h2>
        ${behavioralQuestions || "<p class='meta'>None generated.</p>"}

        <h2>Preparation Plan</h2>
        ${prepPlan || "<p class='meta'>No preparation plan generated.</p>"}
    `

    return generatePdfFromHtml(baseHtml(`Interview Report - ${report.title || ""}`, bodyHtml))
}

/**
 * @name exportChat
 * @description Export a chat conversation as PDF.
 */
async function exportChat(chat) {
    const messages = (chat.messages || []).map(m => {
        const role = m.role === "user" ? "Candidate" : "AI Coach"
        return `
            <div class="section">
                <p class="meta"><strong>${role}</strong> &middot; ${new Date(m.createdAt).toLocaleString()}</p>
                <div><pre>${escapeHtml(m.content)}</pre></div>
            </div>
        `
    }).join("")

    const bodyHtml = `
        <h1>Chat Conversation</h1>
        <p class="meta">${escapeHtml(chat.title || "Untitled Chat")}</p>
        ${messages || "<p class='meta'>No messages.</p>"}
    `

    return generatePdfFromHtml(baseHtml(`Chat - ${chat.title || "Conversation"}`, bodyHtml))
}

/**
 * @name exportMockInterview
 * @description Export a mock interview session as PDF.
 */
async function exportMockInterview(session) {
    const questions = (session.questions || []).map((q, i) => {
        const evalScore = q.evaluation?.score !== null && q.evaluation?.score !== undefined ? `${q.evaluation.score}/10` : "N/A"
        return `
            <div class="section">
                <h3>Q${i + 1}: ${escapeHtml(q.question)}</h3>
                <p><strong>Answer:</strong> ${escapeHtml(q.answer || "No answer")}</p>
                <p><strong>Score:</strong> <span class="score-badge">${evalScore}</span></p>
                ${q.evaluation?.strengths?.length ? `<p><strong>Strengths:</strong></p><ul>${q.evaluation.strengths.map(s => `<li>${escapeHtml(s)}</li>`).join("")}</ul>` : ""}
                ${q.evaluation?.weaknesses?.length ? `<p><strong>Weaknesses:</strong></p><ul>${q.evaluation.weaknesses.map(w => `<li>${escapeHtml(w)}</li>`).join("")}</ul>` : ""}
                ${q.evaluation?.betterAnswer ? `<p><strong>Better Answer:</strong> ${escapeHtml(q.evaluation.betterAnswer)}</p>` : ""}
                ${q.evaluation?.tips?.length ? `<p><strong>Tips:</strong></p><ul>${q.evaluation.tips.map(t => `<li>${escapeHtml(t)}</li>`).join("")}</ul>` : ""}
            </div>
        `
    }).join("")

    const answered = (session.questions || []).filter(q => q.answer).length
    const scores = (session.questions || [])
        .map(q => q.evaluation?.score)
        .filter(s => s !== null && s !== undefined)
    const avgScore = scores.length > 0 ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : "N/A"

    const bodyHtml = `
        <h1>Mock Interview Report</h1>
        <p class="meta">${escapeHtml(session.type)} interview</p>

        <div class="info-grid">
            <div class="info-card"><strong>Duration</strong><span>${session.durationMin || 30} min</span></div>
            <div class="info-card"><strong>Questions Answered</strong><span>${answered}</span></div>
            <div class="info-card"><strong>Average Score</strong><span class="score-badge">${avgScore}</span></div>
        </div>

        <h2>Questions &amp; Evaluations</h2>
        ${questions || "<p class='meta'>No questions.</p>"}
    `

    return generatePdfFromHtml(baseHtml(`Mock Interview - ${session.type}`, bodyHtml))
}

/**
 * @name exportRoadmap
 * @description Export a career roadmap as PDF.
 */
async function exportRoadmap(roadmap) {
    const weeks = (roadmap.weeks || []).map(w =>
        `<div class="section">
            <h3>Week ${w.week}: ${escapeHtml(w.title)}</h3>
            <p class="meta"><strong>Focus:</strong> ${escapeHtml(w.focus)}</p>
            <p><strong>Tasks:</strong></p>
            <ul>${(w.tasks || []).map(t => `<li>${escapeHtml(t)}</li>`).join("")}</ul>
            ${w.resources?.length ? `<p><strong>Resources:</strong></p><ul>${w.resources.map(r => `<li>${escapeHtml(r)}</li>`).join("")}</ul>` : ""}
        </div>`
    ).join("")

    const bodyHtml = `
        <h1>Career Roadmap</h1>
        <p class="meta">${escapeHtml(roadmap.title || "Career Roadmap")}</p>
        ${roadmap.summary ? `<p>${escapeHtml(roadmap.summary)}</p>` : ""}
        ${weeks || "<p class='meta'>No weeks generated.</p>"}
    `

    return generatePdfFromHtml(baseHtml(`Roadmap - ${roadmap.title || "Career"}`, bodyHtml))
}

module.exports = {
    exportInterviewReport,
    exportChat,
    exportMockInterview,
    exportRoadmap,
    generatePdfFromHtml,
    escapeHtml
}
